import type { Config } from "tailwindcss"

export default {
    content: ["./index.html", "./app/**/*.tsx"],
    theme: {
        fontFamily: {
            sans: [
                "-apple-system",
                "BlinkMacSystemFont",
                "avenir next",
                "avenir",
                "segoe ui",
                "helvetica neue",
                "helvetica",
                "Cantarell",
                "Ubuntu",
                "roboto",
                "noto",
                "arial",
                "sans-serif",
            ],
            serif: [
                "-apple-system-ui-serif",
                "ui-serif",
                "Georgia",
                "Iowan Old Style",
                "Apple Garamond",
                "Baskerville",
                "Times New Roman",
                "Droid Serif",
                "Times",
                "Source Serif Pro",
                "serif",
                "Apple Color Emoji",
                "Segoe UI Emoji",
                "Segoe UI Symbol",
            ],
            mono: [
                "ui-monospace",
                "SFMono-Regular",
                "Andale Mono",
                "Ubuntu Mono",
                "Menlo",
                "Consolas",
                "Monaco",
                "Liberation Mono",
                "Lucida Console",
                "monospace",
            ],
        },
    },
    plugins: [],
    darkMode: "media",
} satisfies Config
